## Import Python Packages and Get Data

In [1]:
# Improt ncessary packages
import os
import numpy as np
import earthpy as et


In [6]:
# Download .txt with avg monthly precip (inches)
monthly_precip_url = 'https://ndownloader.figshare.com/files/12565616'
et.data.get_data(url=monthly_precip_url)

# Download .csv of precip data for 2002 and 2013 (inches)
precip_2002_2013_url = 'https://ndownloader.figshare.com/files/12707792'
et.data.get_data(url=precip_2002_2013_url)

'C:\\Users\\fnasr\\earth-analytics\\data\\earthpy-downloads\\monthly-precip-2002-2013.csv'

In [7]:
# Set working directory to earth-analytics
os.chdir(os.path.join(et.io.HOME, 'earth-analytics'))

In [10]:
# Import average monthly precip to numpy array
fname = os.path.join('data', 'earthpy-downloads', 'avg-monthly-precip.txt')
ave_monthly_precip = np.loadtxt(fname)
print(ave_monthly_precip)

[0.7  0.75 1.85 2.93 3.05 2.02 1.93 1.62 1.84 1.31 1.39 0.84]


In [11]:
# Import monthly precip for 2002 and 2013 to numpy array
fname1 = os.path.join('data', 'earthpy-downloads', 'monthly-precip-2002-2013.csv')
precip_2002_2013 = np.loadtxt(fname1, delimiter=',')
print(precip_2002_2013)

[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]


## Check Dimensions and Shape of Numpy Arrays


In [13]:
ave_monthly_precip.ndim

1

In [14]:
precip_2002_2013.ndim

2

In [15]:
ave_monthly_precip.shape

(12,)

In [16]:
precip_2002_2013.shape

(2, 12)

In [17]:
# Use assignment operator to convert values from in to mm
ave_monthly_precip *= 25.4

In [18]:
ave_monthly_precip

array([17.78 , 19.05 , 46.99 , 74.422, 77.47 , 51.308, 49.022, 41.148,
       46.736, 33.274, 35.306, 21.336])

In [19]:
print(precip_2002_2013)

[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]


In [20]:
precip_2002_2013 *= 25.4
precip_2002_2013


array([[ 27.178,  11.176,  38.1  ,   5.08 ,  81.28 ,  29.972,   2.286,
         36.576,  38.608,  61.976,  19.812,   0.508],
       [  6.858,  28.702,  43.688, 105.156,  67.564,  15.494,  26.162,
         35.56 , 461.264,  56.896,   7.366,  12.7  ]])

In [21]:
print(precip_2002_2013)

[[ 27.178  11.176  38.1     5.08   81.28   29.972   2.286  36.576  38.608
   61.976  19.812   0.508]
 [  6.858  28.702  43.688 105.156  67.564  15.494  26.162  35.56  461.264
   56.896   7.366  12.7  ]]


## Run Summary Statistics on One-dimensional Numpy Arrays

In [23]:
# Create variable with mean value
mean_ave_precip = np.mean(ave_monthly_precip)

print('mean average monthly precipitation:', mean_ave_precip)

mean average monthly precipitation: 42.820166666666665


In [24]:
# Create variable with median value
medina_ave_precip = np.median(ave_monthly_precip)

print("median average precipitation", medina_ave_precip)

median average precipitation 43.942


In [26]:
# Calculate and print minimum and maximum values
min_ave_precip = np.min(ave_monthly_precip)
print("minimum average precipitation", min_ave_precip)
print("maximum average precipitation", np.max(ave_monthly_precip))

minimum average precipitation 17.779999999999998
maximum average precipitation 77.46999999999998


## Calculate Summary Statistics Across Rows

In [27]:
# Visually identify max value across the rows of precip_2002_2013
print(precip_2002_2013)

[[ 27.178  11.176  38.1     5.08   81.28   29.972   2.286  36.576  38.608
   61.976  19.812   0.508]
 [  6.858  28.702  43.688 105.156  67.564  15.494  26.162  35.56  461.264
   56.896   7.366  12.7  ]]


In [28]:
# Maximum value for each month across years 2002 and 2013
print(np.max(precip_2002_2013, axis=0))

[ 27.178  28.702  43.688 105.156  81.28   29.972  26.162  36.576 461.264
  61.976  19.812  12.7  ]


In [29]:
# Create new array of the maximum value for each month
precip_2002_2013_monthly_max = np.max(precip_2002_2013, axis=0)

type(precip_2002_2013_monthly_max)

numpy.ndarray

In [30]:
# Visually identify max value across the rows of precip_2002_2013
print(precip_2002_2013)

[[ 27.178  11.176  38.1     5.08   81.28   29.972   2.286  36.576  38.608
   61.976  19.812   0.508]
 [  6.858  28.702  43.688 105.156  67.564  15.494  26.162  35.56  461.264
   56.896   7.366  12.7  ]]


In [32]:
# Maximum value for each year 2002 and 2013
print(np.max(precip_2002_2013, axis=1))

[ 81.28  461.264]
