## Dimensionality of Numpy Arrays


In [2]:
## Import numpy with alias np
import numpy as np


In [4]:
# Monthly avg precip for Jan through Mar in Boulder, CO
ave_monthly_precip = np.array([0.7, 0.75, 1.85])
print(ave_monthly_precip)

[0.7  0.75 1.85]


In [6]:
# Monthly precip for Jan through Mar in 2002 and 2013
precip_2002_2013 = np.array([
    [1.07, 0.44, 1.05],
    [0.27, 1.13, 1.72]
])
print(precip_2002_2013)

[[1.07 0.44 1.05]
 [0.27 1.13 1.72]]
